platform :ios, '7.0'
#use_frameworks!

target 'CommonASIUtilDemo' do
  pod 'ASIHTTPRequest', '~> 1.8.2'
  
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'SVProgressHUD', '~> 1.1.3'
  
  pod 'JSONModel', '~> 1.1.0'
end

target 'CommonASIUtilDemoTests' do
   pod 'ASIHTTPRequest', '~> 1.8.2'
end