platform :ios, '7.0'
#use_frameworks!

target 'CommonAFNUtilDemo' do
  pod 'AFNetworking', '~> 2.6.3'
#  pod 'ASIHTTPRequest', '~> 1.8.2'
#  pod 'Reachability', '~> 3.2'
  pod 'CocoaAsyncSocket', '~> 7.4.1'
  
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'SVProgressHUD', '~> 1.1.3'
  
  pod 'JSONModel', '~> 1.1.0'
end

target 'CommonAFNUtilDemoTests' do
   pod 'AFNetworking', '~> 2.6.3'
#   pod 'ASIHTTPRequest', '~> 1.8.2'
   pod 'CocoaAsyncSocket', '~> 7.4.1'
end