platform :ios, '7.0'
#use_frameworks!

target 'CommonAFNUtilDemo' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'CocoaAsyncSocket', '~> 7.4.1'
  
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'SVProgressHUD', '~> 2.1.2'
  
  pod 'JSONModel', '~> 1.1.0'
  pod 'Mantle', '~> 1.5.8'
  
  pod 'OpenUDID', '~> 1.0.0'
  
  pod 'CJBaseUIKit/UIImage+CJCategory', '~> 0.0.9'
  
end

target 'CommonAFNUtilDemoTests' do
   pod 'AFNetworking', '~> 3.1.0'
   pod 'CocoaAsyncSocket', '~> 7.4.1'
end
