platform :ios, '7.0'
#use_frameworks!

target 'CJNetworkDemo' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'CocoaAsyncSocket', '~> 7.4.1'
  
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'SVProgressHUD', '~> 2.1.2'
  
#  pod 'JSONModel', '~> 1.1.0'
#  pod 'Mantle', '~> 2.1.0'
  
  pod 'OpenUDID', '~> 1.0.0'
  
  pod 'Masonry'
  pod 'CJBaseUIKit/CJAlert', '~> 0.2.2'
  pod 'CJBaseUtil/CJDataUtil', '~> 0.3.0'
  pod 'CJBaseUtil/CJIndentedStringUtil'
end

target 'CJNetworkDemoTests' do
   pod 'AFNetworking', '~> 3.1.0'
   pod 'CocoaAsyncSocket', '~> 7.4.1'
end
