platform :ios, '8.0'
#use_frameworks!
inhibit_all_warnings!

post_install do |installer|
    
    puts 'Determining pod project minimal deployment target'
    
    pods_project = installer.pods_project
    deployment_target_key = 'IPHONEOS_DEPLOYMENT_TARGET'
    deployment_targets = pods_project.build_configurations.map{ |config| config.build_settings[deployment_target_key] }
    minimal_deployment_target = deployment_targets.min_by{ |version| Gem::Version.new(version) }
    
    puts 'Minimal deployment target is ' + minimal_deployment_target
    puts 'Setting each pod deployment target to ' + minimal_deployment_target
    
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings[deployment_target_key] = minimal_deployment_target
        end
    end
end


target 'CJNetworkDemo' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'CocoaAsyncSocket', '~> 7.4.1'
  pod 'YYCache', '~> 1.0.4'
  pod 'MJExtension', '~> 3.0.15.1'
  
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'SVProgressHUD', '~> 2.1.2'
  
#  pod 'JSONModel', '~> 1.1.0'
#  pod 'Mantle', '~> 2.1.0'
  
  pod 'OpenUDID', '~> 1.0.0'
  
  pod 'Masonry'
  pod 'CJBaseUIKit/CJAlert', '~> 0.2.2'
  pod 'CJBaseUtil/CJDataUtil'
  pod 'CJBaseUtil/CJIndentedStringUtil'
  pod 'CJBaseUtil/CJLog', '~> 0.3.1'
end

target 'CJNetworkDemoTests' do
   pod 'AFNetworking', '~> 3.1.0'
   pod 'CocoaAsyncSocket', '~> 7.4.1'
end
